accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<str:username>/follow/', views.follow, name='follow'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments, name='comment'),
    path('movies/<int:movie_pk>/comments/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('movies/<int:pk>/likes/', views.likes, name='likes')
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    following = models.ManyToManyField('self', related_name="follower")

movies/models.py
from django.db import models
from django.conf import settings

class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_users")

class Comments(models.Model):
    content = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')

movies/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'description')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_GET, require_POST, require_safe, require_http_methods
from .forms import CustomUserCreationForm, CustomUserChangeForm

from .forms import CustomUserCreationForm, CustomUserChangeForm


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()

    context = {'form': form}
    return render(request, 'accounts/login.html', context)

@require_POST
def logout(request):
    auth_logout(request)
    return redirect('movies:index')

@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index') 
    else:
        form = CustomUserCreationForm()
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)

@require_POST
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('movies:index')

@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index') 
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {'form': form}
    return render(request, 'accounts/update.html', context)

@require_http_methods(['GET', 'POST'])
def password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index') 
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form}
    return render(request, 'accounts/password.html', context)

@require_GET
def profile(request, username):
    user = get_user_model().objects.get(username=username)
    context = {'user': user}
    return render(request, 'accounts/profile.html', context)

@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_user_model().objects.get(pk=user_pk)
        if request.user in person.followers.all():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
        return redirect('accounts:profile', person.username)
    else:
        return redirect('accounts:login')

movies/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm


def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form': form,
    }
    return render(request, 'movies/create.html', context)


def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)


def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')


def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'movie': movie,
        'form': form,
    }
    return render(request, 'movies/update.html', context)

def comments(request, pk):
    pass

def delete_comment(request, movie_pk, comment_pk):
    pass

def likes(request, movie_pk):
    pass

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>Login</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="로그인">
  </form>
{% endblock content %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}

{% block content %}
  <h1>비밀번호 변경</h1>
  <form action="{% url 'accounts:password' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="비밀번호 변경">
  </form>
  <a href="{% url 'movies:index' %}">목록보기</a>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ user.username }}님의 프로필</h1>
    <div>
        <div>팔로잉 : {{ user.followings.count }} | 팔로워 : {{ user.followers.count }}</div>    
        {% if request.user != user %}
            <form action="{% url 'accounts:follow' user.pk %}" method="POST">
                {% csrf_token %}
                {% if request.user in user.followers.all %}
                    <button type="submit" class="btn btn-danger">언팔로우</button>
                {% else %}
                    <button type="submit" class="btn btn-primary">팔로우</button>
                {% endif %}
            </form>
        {% endif %}    

    </div>
    <hr>

    <h5>{{ user.username }}님의 작성글</h5>
    <hr>
    {% for article in user.article_set.all %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ article.title }}</h5>
                <p class="card-text">{{ article.content }}</p>
                <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">자세히 보기</a>
            </div>
        </div>
    {% endfor %}
    <br><br>

    <h5>{{ user.username }}님이 좋아요한 게시물</h5>
    <hr>
    {% for article in user.like_articles.all %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ article.title }}</h5>
                <p class="card-text">{{ article.content }}</p>
                <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">자세히 보기</a>
            </div>
        </div>
    {% endfor %}

    <br><br>    
    <a href="{% url 'articles:index' %}" class="btn btn-success">목록보기</a>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원가입</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="회원가입">
  </form>
  <a href="{% url 'movies:index' %}">목록보기</a>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원정보수정</h1>
  <form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="수정완료">
  </form>
  <a href="{% url 'movies:index' %}">목록보기</a>
{% endblock content %}

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <hr>
  <form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
  <hr>
  <a href="{% url 'movies:index' %}">BACK</a>
{% endblock %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <hr>
  <div>
    <h5>{{ movie.title }}</h5>
    <p>{{ movie.description }}</p>
  </div>
  <a href="{% url 'movies:index' %}">BACK</a>
  <hr>
{% endblock  %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'movies:create' %}">[CREATE]</a>
  <hr>
  {% for movie in movies %}
    <a href="{% url 'movies:detail' movie.pk %}"><p>{{ movie.title }}</p></a>
    <hr>
  {% endfor %}
{% endblock %}

movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <hr>
  <form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">TITLE</label>
      <input type="text" id="title" name="title" value="{{ movie.title }}">
    </div>
    <div>
      <label for="description">DESCRIPTION</label>
      <textarea id="description" rows="3" name="description">{{ movie.description }}</textarea>
    </div>
    <input type="reset" value="Reset">
    <button type="submit">Submit</button>
  </form>
  <hr>
  <a href="{% url 'movies:detail' movie.pk %}">BACK</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>